### ISSUE TITLE
File integrity manifest includes temporary file QrReaderTest.php~ (installed from rpm packages)

### ISSUE THREAD

**Issue by GlennMatthys** [owncloud/twofactor_totp#198]
### Steps to reproduce
1. Install Owncloud from RPM package https://download.owncloud.org/download/repositories/10.5.0/CentOS_8/noarch/owncloud-complete-files-10.5.0-4.1.noarch.rpm
2. Login as admin

### Expected behaviour
No "There were problems with the code integrity check." message

### Actual behaviour
"There were problems with the code integrity check." message appears. (See signing status below)

### Server configuration
**Operating system**: CentOS Linux release 8.2.2004 (Core)

**Web server:** Apache/2.4.37 (centos)

**Database:** mariadb-server-5.5.64

**PHP version:** PHP 7.3.5

**ownCloud version:** 10.5

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** RPM repository

**Signing status (ownCloud 9.0 and above):** https://gist.github.com/GlennMatthys/2f4270e1785b9167570b4b3ebe391390

**The content of config/config.php:** https://gist.github.com/GlennMatthys/7810e55a0c7609f0e2374d81b6e2f928

**List of activated apps:**

```
Enabled:
  - activity: 2.5.4
  - configreport: 0.2.0
  - dav: 0.6.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.3
  - files_sharing: 0.13.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - market: 0.6.0
  - provisioning_api: 0.5.0
  - updatenotification: 0.2.1
  - user_ldap: 0.15.2
Disabled:
  - admin_audit
  - announcementcenter
  - comments
  - customgroups
  - encryption
  - enterprise_key
  - external
  - files_antivirus
  - files_classifier
  - files_external_dropbox
  - files_external_ftp
  - files_ldap_home
  - files_pdfviewer
  - firewall
  - firstrunwizard
  - guests
  - notifications
  - oauth2
  - password_policy
  - ransomware_protection
  - sharepoint
  - systemtags
  - systemtags_management
  - templateeditor
  - theme-enterprise
  - twofactor_totp
  - user_external
  - user_shibboleth
  - windows_network_drive
  - wopi
  - workflow
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Operating system:** Windows 10 Version 1909 (OS Build 18363.1016)

**Comment by phil-davis** [comment]
I pinged the repo owner https://github.com/khanamiryan/php-qrcode-detector-decoder/pull/96#issuecomment-731706341
And transferred this issue to twofactor_totp

Let's see if we get any response.

**Comment by Serverprogetti** [comment]
Hello,
I am also facing the same issue, 

Operating system: CentOS Linux release  7.8.2003 (Core)

Web server: httpd-2.4.6-93.el7.centos.x86_64

Database: mariadb-5.5.65-1.el7.x86_64

PHP version: PHP 7.2.34

ownCloud version: 10.5

Let's see if we get any response.
Thanks.

**Comment by phil-davis** [comment]
Should be fixed by #199

**Comment by gopromaster** [comment]
I still get the above warning, namely:

`Results
=======
- twofactor_totp
	- FILE_MISSING
		- vendor/khanamiryan/qrcode-detector-decoder/tests/QrReaderTest.php~
`

OS: Ubuntu 20.04.1 LTS

Web server: Apache/2.4.41

Database: mariadb  Ver 15.1 Distrib 10.3.25-MariaDB

PHP version: PHP 7.4.13

ownCloud version: 10.5

I thought this was fixed?

**Comment by phil-davis** [comment]
It needs a release of this app. See issue #200 
I don't know when someone will do a release.

**Comment by jnweiger** [comment]
In https://github.com/owncloud/twofactor_totp/releases/download/v0.7.0/twofactor_totp-0.7.0.tar.gz we have
```
ll twofactor_totp/vendor/khanamiryan/qrcode-detector-decoder/tests/
total 24
drwxr-xr-x 3 www-data root 4096 Jun 19  2020 ./
drwxr-xr-x 4 www-data root 4096 Jun 19  2020 ../
-rw-r--r-- 1 www-data root  401 Jun 19  2020 bootstrap.php
drwxr-xr-x 2 www-data root 4096 Jun 19  2020 qrcodes/
-rw-r--r-- 1 www-data root  324 Jun 19  2020 QrReaderTest.php
-rw-r--r-- 1 www-data root  324 Jun 19  2020 QrReaderTest.php~
```

**Comment by phil-davis** [comment]
And in https://github.com/owncloud/twofactor_totp/releases/download/v0.7.1RC1/twofactor_totp-0.7.1RC1.tar.gz the file `QrReaderTest.php~` is not there, which is good. This problem should be fixed in 0.7.1

**Comment by jnweiger** [comment]
And twofactor_totp is no longer part of the server-complete bundle as per server 10.6.0 -- so the issue would not show up there either.
